FROM centos:7

RUN yum -y --enablerepo=extras install epel-release && yum clean all && yum -y update
RUN yum -y install wget
RUN yum -y install make
RUN yum install gcc -y
RUN yum install zlib-devel -y
RUN yum install libffi-devel -y
RUN yum install openssl-devel -y
RUN wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz && tar xzf Python-3.7.2.tgz
RUN cd Python-3.7.2 && ./configure --enable-optimizations && make altinstall

USER root
RUN yum install dnf -y
RUN yum install sudo -y
RUN sudo yum -y install epel-release
RUN sudo yum -y install jq -y
RUN yum install --assumeyes python3-pip

RUN echo $'[kubernetes] \n\
name=Kubernetes \n\
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 \n\
enabled=1 \n\
gpgcheck=1 \n\
repo_gpgcheck=1 \n\
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg \n '\
> /etc/yum.repos.d/kubernetes.repo
RUN yum install -y kubectl

ARG USER_ID=997
ARG GROUP_ID=994
RUN groupadd -g $GROUP_ID centos && \
    useradd -u $USER_ID -s /bin/sh -g centos centos
RUN echo "root:root" | chpasswd
RUN echo "centos:centos" | chpasswd
RUN echo "centos ALL=(ALL) ALL" > /etc/sudoers
RUN echo "centos ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers
RUN echo "root ALL=(ALL) ALL" > /etc/sudoers
RUN echo "root ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers

RUN sudo yum install git -y

RUN wget https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz

ENV GOPATH $HOME/go
ENV GOROOT="/usr/local/go"
ENV GOBIN="/root/go/bin"
ENV PATH=$PATH:$GOROOT/bin:$GOBIN:$GOPATH:/usr/local/bin/:/usr/local/go/bin

RUN sudo mkdir -p $HOME/go
ADD src/ $HOME/go/src
ADD pkg/ $HOME/go/pkg
ADD bin/ $HOME/go/bin
RUN sudo chmod 777 $HOME/go/src
RUN sudo chmod 777 $HOME/go/pkg
RUN sudo chmod 777 $HOME/go/bin

RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.10.0/kind-linux-amd64
RUN chmod +x kind
RUN sudo mv kind /usr/local/bin/

ARG DOCKER_CLIENT=docker-20.10.2.tgz
RUN cd /tmp/ && curl -sSL -O https://download.docker.com/linux/static/stable/x86_64/docker-20.10.2.tgz\
&& tar zxf docker-20.10.2.tgz \
&& mkdir -p /usr/local/bin \
&& mv ./docker/docker /usr/local/bin \
&& chmod +x /usr/local/bin/docker \
&& rm -rf /tmp/*

RUN yum install unzip -y
RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
RUN unzip awscli-bundle.zip
# aws only use python3.7
RUN sudo ln -fs /usr/local/bin/python3.7 /usr/bin/python
RUN sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
RUN aws --version
RUN rm awscli-bundle.zip

WORKDIR $HOME/go/src/github.com/kong/kubernetes-ingress-controller
ADD go.mod .
ADD go.sum .
RUN GO111MODULE=on go mod download
